version: "3.9"  
---
x-airflow-common:
  &airflow-common
  # In order to add custom dependencies or upgrade provider distributions you can use your extended image.
  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
  # image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.0.1}
  build:
    context: .
    args:
      - DOCKER_GID=${DOCKER_GID}
  environment:
    &airflow-common-env
    AIRFLOW_VAR_MINIO_ENDPOINT: http://minio:9000
    AIRFLOW_VAR_MINIO_ACCESS_KEY: minio_access_key
    AIRFLOW_VAR_MINIO_SECRET_KEY: minio_secret_key
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    PYTHONPATH: /opt/airflow
    # AIRFLOW_CONN_SPARK_DEFAULT: spark://spark-master:7077
    # yamllint disable rule:line-length
    # Use simple http server on scheduler for health checks
    # See https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/check-health.html#scheduler-health-check-server
    # yamllint enable rule:line-length
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    SPARK_CONF_DIR: '/opt/airflow/config'
    
    # WARNING: Use _PIP_ADDITIONAL_REQUIREMENTS option ONLY for a quick checks
    # for other purpose (development, test and especially production usage) build/extend Airflow image.
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    # _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-apache-spark"
    # The following line can be used to set a custom config file, stored in the local config folder
    AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/scripts:/opt/airflow/scripts
    - ${AIRFLOW_PROJ_DIR:-.}/feature_repo:/opt/airflow/feature_repo
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ./jars:/opt/spark/extra-jars
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  minio:
    image: minio/minio
    container_name: datalake-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server --console-address ":9001" /data

  metastore_db:
    container_name: datalake-metastore-db
    image: postgres:11
    # ports:
    #   - '5433:5432' # Access via Thrift protocol
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore

  hive-metastore:
    container_name: datalake-hive-metastore
    image: 'starburstdata/hive:3.1.2-e.18'
    ports:
      - '9083:9083' # Access via Thrift protocol
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      # HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/ # HDFS config, we don't need it
      # HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin" # We also don't need it
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio_access_key
      S3_SECRET_KEY: minio_secret_key
      S3_PATH_STYLE_ACCESS: "true"
      # Below arguments exist for no reasons, but
      # we can not live without it
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
    depends_on:
      - metastore_db

#   trino:
#     # ports:
#     #   - "8080:8080"
#     container_name: datalake-trino
#     image: "trinodb/trino:410"
#     volumes:
#       - ./trino:/etc/trino
#     depends_on:
#       - hive-metastore

  redis:
    image: redis:latest
    container_name: airflow-redis
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s

  offline-ds:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: iot_db
    command: ['postgres', '-c', 'wal_level=logical']
    volumes:
      - offline-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully


  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        airflow connections add 'spark_default' \
          --conn-json '{
              "conn_type": "spark",
              "host": "spark://spark-master",
              "port": "7077"
          }'
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
          export AIRFLOW_UID=$(id -u)
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        echo
        echo "Creating missing opt dirs if missing:"
        echo
        mkdir -v -p /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Airflow version:"
        /entrypoint airflow version
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Running airflow config list to create default config file if missing."
        echo
        /entrypoint airflow config list >/dev/null
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Change ownership of files in /opt/airflow to ${AIRFLOW_UID}:0"
        echo
        chown -R "${AIRFLOW_UID}:0" /opt/airflow/
        echo
        echo "Change ownership of files in shared volumes to ${AIRFLOW_UID}:0"
        echo
        chown -v -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,config}
        echo
        echo "Files in shared volumes:"
        echo
        ls -la /opt/airflow/{logs,dags,plugins,config}

    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   container_name: cdc-zookeeper
  #   ports:
  #     - "2181:2181" # host_port:container_port
  #   healthcheck:
  #     test: echo srvr | nc zookeeper 2181 || exit 1
  #     start_period: 10s
  #     retries: 20
  #     interval: 10s
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181 # Client will connect to this port to communicate with zookeeper
  #     ZOOKEEPER_TICK_TIME: 2000 # Basic time unit for timing (2000 ms)

  # # Kafka broker, each broker can be considered as a node
  # broker:
  #   image: confluentinc/cp-server:7.5.0
  #   container_name: cdc-broker
  #   depends_on:
  #     zookeeper:
  #       condition: service_healthy
  #   ports:
  #     - "9092:9092"
  #     - "9101:9101"
  #   healthcheck:
  #     test: nc -z localhost 9092 || exit -1
  #     start_period: 15s
  #     interval: 5s
  #     timeout: 10s
  #     retries: 10
  #   environment:
  #     # ID of the broker in a cluster
  #     KAFKA_BROKER_ID: 1 
  #     # Connect to Zoo Keeper for distributed coordination and leader election
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     # Define how clients connect to brokers
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
  #     # How many copies are maintained for fault tolerance
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     # How long a new consumer should wait before participating in a consumer group rebalance
  #     # we give consumers some 
  #     # Schema Registry URL for storing and managing Avro schemas
  #     KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081

  # # Store Avro schemas for topics to ensure schema compatibility
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:7.5.0
  #   container_name: cdc-schema-registry
  #   depends_on:
  #     broker:
  #       condition: service_healthy
  #   # ports:
  #   # - "8081:8081"
  #   healthcheck:
  #     start_period: 10s
  #     interval: 10s
  #     retries: 20
  #     test: curl --user superUser:superUser --fail --silent --insecure http://localhost:8081/subjects --output /dev/null || exit 1
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:7.5.0
  #   container_name: cdc-control-center
  #   depends_on:
  #     broker:
  #       condition: service_healthy
  #     schema-registry:
  #       condition: service_healthy
  #     debezium:
  #       condition: service_healthy
  #   ports:
  #     - "9021:9021"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9021/healthcheck"] # Adjust the URL and options as needed
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
  #     CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'debezium:8083'
  #     CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  #     # How many copies for control-center internal topics
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #     # Number of partitions for control-center internal topics
  #     CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
  #     # CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
  #     # Health check endpoint to monitor status of connectors
  #     CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: '/connectors'
  #     # How many copies for confluent metrics topics
  #     CONFLUENT_METRICS_TOPIC_REPLICATION: 1

  # # CDC platform to capture changes in DB
  # # and stream them to Kafka
  # debezium:
  #   image: debezium/connect:1.9
  #   container_name: cdc-debezium
  #   depends_on:
  #     broker:
  #       condition: service_healthy
  #     schema-registry:
  #       condition: service_healthy
  #     zookeeper:
  #       condition: service_healthy
  #   healthcheck:
  #     test:
  #       [
  #         'CMD',
  #         'curl',
  #         '--silent',
  #         '--fail',
  #         '-X',
  #         'GET',
  #         'http://localhost:8083/connectors',
  #       ]
  #     start_period: 10s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     BOOTSTRAP_SERVERS: broker:29092
  #     GROUP_ID: 1
  #     CONFIG_STORAGE_TOPIC: connect_configs
  #     OFFSET_STORAGE_TOPIC: connect_offsets
  #     # Set to Avro for higher performance
  #     # KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     # VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  #     KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #     VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  #     CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  #     CONNECT_TOPIC_CREATION_ENABLE: true

  # # Debezium UI
  # debezium-ui:
  #   image: debezium/debezium-ui:latest
  #   container_name: debezium-ui
  #   hostname: debezium-ui
  #   depends_on:
  #     debezium:
  #       condition: service_healthy
  #   ports:
  #     - '8082:8080'
  #   environment:
  #     KAFKA_CONNECT_URIS: http://debezium:8083

  spark-master:
    # image: jupyter/pyspark-notebook:spark-3.5.0
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark_master
    user: root
    ports:
      - "8888:8888" # Jupyter Lab UI
      - "8080:8080"
      - "4040:4040" # Spark UI
      - "7077:7077"
    volumes:
      - ./spark-code:/home/jovyan/work
      - ./scripts:/home/jovyan/scripts
      - ./jars:/opt/spark/extra-jars
      - ./config:/usr/local/spark/conf
    command: >
      bash -c "
      /usr/local/spark-3.5.0-bin-hadoop3/sbin/start-master.sh && 
      /usr/local/bin/start-notebook.sh
      "
    environment:
      - SPARK_MASTER_HOST=spark-master
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  spark-worker:
    # image: jupyter/pyspark-notebook:spark-3.5.0
    build:
      context: .
      dockerfile: Dockerfile.spark
    # container_name: spark_worker
    user: root
    depends_on:
      - spark-master
    command: >
       /usr/local/spark-3.5.0-bin-hadoop3/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./jars:/opt/spark/extra-jars

  feature_store:
    container_name: feature_store
    build:
      context: ./feature_repo
      dockerfile: Dockerfile
    environment:
      - SPARK_CONF_DIR=/app/conf
      - AWS_ACCESS_KEY_ID=minio_access_key
      - AWS_SECRET_ACCESS_KEY=minio_secret_key
    volumes:
      - ./config:/app/conf
      - ./jars:/app/jars
    depends_on:
      - metastore_db

  mlflow:
    image: python:3.9-slim
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio_access_key
      - AWS_SECRET_ACCESS_KEY=minio_secret_key
    command: >
      bash -c "pip install mlflow boto3 psycopg2-binary &&
               mlflow server --host 0.0.0.0
               --backend-store-uri postgresql+psycopg2://airflow:airflow@postgres/mlflow_db
               --default-artifact-root s3://mlflow/"
    depends_on:
      - postgres
      - minio


volumes:
  postgres-db-volume:
  offline-db-volume:
  minio_storage: