# Start from the base Jupyter image
FROM jupyter/pyspark-notebook:spark-3.5.0

# Switch to the root user to install packages
USER root

# Update package lists and install rsync
RUN apt-get update && \
    apt-get install -y --no-install-recommends rsync && \
    # Clean up to reduce image size
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*