#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_HIVE_USER WITH PASSWORD '$POSTGRES_HIVE_PASSWORD';
    CREATE DATABASE hive;
    GRANT ALL PRIVILEGES ON DATABASE hive TO $POSTGRES_HIVE_USER;
EOSQL