CREATE TABLE hive.iot_lakehouse.traffic_test (
   -- All 115 feature columns
   "H_L5_weight" DOUBLE,
   "H_L5_mean" DOUBLE,
   "H_L5_variance" DOUBLE,
   "H_L3_weight" DOUBLE,
   "H_L3_mean" DOUBLE,
   "H_L3_variance" DOUBLE,
   "H_L1_weight" DOUBLE,
   "H_L1_mean" DOUBLE,
   "H_L1_variance" DOUBLE,
   "H_L0.1_weight" DOUBLE,
   "H_L0.1_mean" DOUBLE,
   "H_L0.1_variance" DOUBLE,
   "H_L0.01_weight" DOUBLE,
   "H_L0.01_mean" DOUBLE,
   "H_L0.01_variance" DOUBLE,
   "HH_L5_weight" DOUBLE,
   "HH_L5_mean" DOUBLE,
   "HH_L5_variance" DOUBLE,
   "HH_L3_weight" DOUBLE,
   "HH_L3_mean" DOUBLE,
   "HH_L3_variance" DOUBLE,
   "HH_L1_weight" DOUBLE,
   "HH_L1_mean" DOUBLE,
   "HH_L1_variance" DOUBLE,
   "HH_L0.1_weight" DOUBLE,
   "HH_L0.1_mean" DOUBLE,
   "HH_L0.1_variance" DOUBLE,
   "HH_L0.01_weight" DOUBLE,
   "HH_L0.01_mean" DOUBLE,
   "HH_L0.01_variance" DOUBLE,
   "HH_jit_L5_weight" DOUBLE,
   "HH_jit_L5_mean" DOUBLE,
   "HH_jit_L5_variance" DOUBLE,
   "HH_jit_L3_weight" DOUBLE,
   "HH_jit_L3_mean" DOUBLE,
   "HH_jit_L3_variance" DOUBLE,
   "HH_jit_L1_weight" DOUBLE,
   "HH_jit_L1_mean" DOUBLE,
   "HH_jit_L1_variance" DOUBLE,
   "HH_jit_L0.1_weight" DOUBLE,
   "HH_jit_L0.1_mean" DOUBLE,
   "HH_jit_L0.1_variance" DOUBLE,
   "HH_jit_L0.01_weight" DOUBLE,
   "HH_jit_L0.01_mean" DOUBLE,
   "HH_jit_L0.01_variance" DOUBLE,
   "HpHp_L5_weight" DOUBLE,
   "HpHp_L5_mean" DOUBLE,
   "HpHp_L5_variance" DOUBLE,
   "HpHp_L3_weight" DOUBLE,
   "HpHp_L3_mean" DOUBLE,
   "HpHp_L3_variance" DOUBLE,
   "HpHp_L1_weight" DOUBLE,
   "HpHp_L1_mean" DOUBLE,
   "HpHp_L1_variance" DOUBLE,
   "HpHp_L0.1_weight" DOUBLE,
   "HpHp_L0.1_mean" DOUBLE,
   "HpHp_L0.1_variance" DOUBLE,
   "HpHp_L0.01_weight" DOUBLE,
   "HpHp_L0.01_mean" DOUBLE,
   "HpHp_L0.01_variance" DOUBLE,
   "MI_dir_L5_weight" DOUBLE,
   "MI_dir_L5_mean" DOUBLE,
   "MI_dir_L5_variance" DOUBLE,
   "MI_dir_L3_weight" DOUBLE,
   "MI_dir_L3_mean" DOUBLE,
   "MI_dir_L3_variance" DOUBLE,
   "MI_dir_L1_weight" DOUBLE,
   "MI_dir_L1_mean" DOUBLE,
   "MI_dir_L1_variance" DOUBLE,
   "MI_dir_L0.1_weight" DOUBLE,
   "MI_dir_L0.1_mean" DOUBLE,
   "MI_dir_L0.1_variance" DOUBLE,
   "MI_dir_L0.01_weight" DOUBLE,
   "MI_dir_L0.01_mean" DOUBLE,
   "MI_dir_L0.01_variance" DOUBLE,
   "MI_src_L5_weight" DOUBLE,
   "MI_src_L5_mean" DOUBLE,
   "MI_src_L5_variance" DOUBLE,
   "MI_src_L3_weight" DOUBLE,
   "MI_src_L3_mean" DOUBLE,
   "MI_src_L3_variance" DOUBLE,
   "MI_src_L1_weight" DOUBLE,
   "MI_src_L1_mean" DOUBLE,
   "MI_src_L1_variance" DOUBLE,
   "MI_src_L0.1_weight" DOUBLE,
   "MI_src_L0.1_mean" DOUBLE,
   "MI_src_L0.1_variance" DOUBLE,
   "MI_src_L0.01_weight" DOUBLE,
   "MI_src_L0.01_mean" DOUBLE,
   "MI_src_L0.01_variance" DOUBLE,
   "MI_src_p_L5_weight" DOUBLE,
   "MI_src_p_L5_mean" DOUBLE,
   "MI_src_p_L5_variance" DOUBLE,
   "MI_src_p_L3_weight" DOUBLE,
   "MI_src_p_L3_mean" DOUBLE,
   "MI_src_p_L3_variance" DOUBLE,
   "MI_src_p_L1_weight" DOUBLE,
   "MI_src_p_L1_mean" DOUBLE,
   "MI_src_p_L1_variance" DOUBLE,
   "MI_src_p_L0.1_weight" DOUBLE,
   "MI_src_p_L0.1_mean" DOUBLE,
   "MI_src_p_L0.1_variance" DOUBLE,
   "MI_src_p_L0.01_weight" DOUBLE,
   "MI_src_p_L0.01_mean" DOUBLE,
   "MI_src_p_L0.01_variance" DOUBLE,
   "HI_dir_L5_weight" DOUBLE,
   "HI_dir_L5_mean" DOUBLE,
   "HI_dir_L5_variance" DOUBLE,
   "HI_dir_L3_weight" DOUBLE,
   "HI_dir_L3_mean" DOUBLE,
   "HI_dir_L3_variance" DOUBLE,
   "HI_dir_L1_weight" DOUBLE,
   "HI_dir_L1_mean" DOUBLE,
   "HI_dir_L1_variance" DOUBLE,
   "HI_dir_L0.1_weight" DOUBLE,
   "HI_dir_L0.1_mean" DOUBLE,
   "HI_dir_L0.1_variance" DOUBLE,
   "HI_dir_L0.01_weight" DOUBLE,
   "HI_dir_L0.01_mean" DOUBLE,
   "HI_dir_L0.01_variance" DOUBLE,
   attack_type VARCHAR,
   
   -- As requested, adding partition columns to the main definition
   device_name VARCHAR,
   dt VARCHAR
)
WITH (
   format = 'PARQUET',
   external_location = 's3a://iot-time-series/processed/',
   partitioned_by = ARRAY['device_name', 'dt']
);

SELECT
    device_name,
    dt,
    attack_type
FROM
    hive.iot_lakehouse.traffic_test
WHERE
    dt >= '2025-06-01';