-- SQL script to create the source table in PostgreSQL.
-- Debezium will monitor this table for changes.

CREATE TABLE iot_raw_data (
    -- Primary key for unique row identification, crucial for Debezium
    id SERIAL PRIMARY KEY,

    -- Timestamp to record when the data was generated
    event_timestamp TIMESTAMPTZ DEFAULT NOW(),

    -- Metadata columns that will be used for partitioning in the lakehouse
    device_name VARCHAR(50),
    attack_type VARCHAR(50),

    -- Feature Columns (115 features)
    "H_L5_weight" DOUBLE PRECISION,
    "H_L5_mean" DOUBLE PRECISION,
    "H_L5_variance" DOUBLE PRECISION,
    "H_L3_weight" DOUBLE PRECISION,
    "H_L3_mean" DOUBLE PRECISION,
    "H_L3_variance" DOUBLE PRECISION,
    "H_L1_weight" DOUBLE PRECISION,
    "H_L1_mean" DOUBLE PRECISION,
    "H_L1_variance" DOUBLE PRECISION,
    "H_L0.1_weight" DOUBLE PRECISION,
    "H_L0.1_mean" DOUBLE PRECISION,
    "H_L0.1_variance" DOUBLE PRECISION,
    "H_L0.01_weight" DOUBLE PRECISION,
    "H_L0.01_mean" DOUBLE PRECISION,
    "H_L0.01_variance" DOUBLE PRECISION,
    "HH_L5_weight" DOUBLE PRECISION,
    "HH_L5_mean" DOUBLE PRECISION,
    "HH_L5_variance" DOUBLE PRECISION,
    "HH_L3_weight" DOUBLE PRECISION,
    "HH_L3_mean" DOUBLE PRECISION,
    "HH_L3_variance" DOUBLE PRECISION,
    "HH_L1_weight" DOUBLE PRECISION,
    "HH_L1_mean" DOUBLE PRECISION,
    "HH_L1_variance" DOUBLE PRECISION,
    "HH_L0.1_weight" DOUBLE PRECISION,
    "HH_L0.1_mean" DOUBLE PRECISION,
    "HH_L0.1_variance" DOUBLE PRECISION,
    "HH_L0.01_weight" DOUBLE PRECISION,
    "HH_L0.01_mean" DOUBLE PRECISION,
    "HH_L0.01_variance" DOUBLE PRECISION,
    "HH_jit_L5_weight" DOUBLE PRECISION,
    "HH_jit_L5_mean" DOUBLE PRECISION,
    "HH_jit_L5_variance" DOUBLE PRECISION,
    "HH_jit_L3_weight" DOUBLE PRECISION,
    "HH_jit_L3_mean" DOUBLE PRECISION,
    "HH_jit_L3_variance" DOUBLE PRECISION,
    "HH_jit_L1_weight" DOUBLE PRECISION,
    "HH_jit_L1_mean" DOUBLE PRECISION,
    "HH_jit_L1_variance" DOUBLE PRECISION,
    "HH_jit_L0.1_weight" DOUBLE PRECISION,
    "HH_jit_L0.1_mean" DOUBLE PRECISION,
    "HH_jit_L0.1_variance" DOUBLE PRECISION,
    "HH_jit_L0.01_weight" DOUBLE PRECISION,
    "HH_jit_L0.01_mean" DOUBLE PRECISION,
    "HH_jit_L0.01_variance" DOUBLE PRECISION,
    "HpHp_L5_weight" DOUBLE PRECISION,
    "HpHp_L5_mean" DOUBLE PRECISION,
    "HpHp_L5_variance" DOUBLE PRECISION,
    "HpHp_L3_weight" DOUBLE PRECISION,
    "HpHp_L3_mean" DOUBLE PRECISION,
    "HpHp_L3_variance" DOUBLE PRECISION,
    "HpHp_L1_weight" DOUBLE PRECISION,
    "HpHp_L1_mean" DOUBLE PRECISION,
    "HpHp_L1_variance" DOUBLE PRECISION,
    "HpHp_L0.1_weight" DOUBLE PRECISION,
    "HpHp_L0.1_mean" DOUBLE PRECISION,
    "HpHp_L0.1_variance" DOUBLE PRECISION,
    "HpHp_L0.01_weight" DOUBLE PRECISION,
    "HpHp_L0.01_mean" DOUBLE PRECISION,
    "HpHp_L0.01_variance" DOUBLE PRECISION,
    "MI_dir_L5_weight" DOUBLE PRECISION,
    "MI_dir_L5_mean" DOUBLE PRECISION,
    "MI_dir_L5_variance" DOUBLE PRECISION,
    "MI_dir_L3_weight" DOUBLE PRECISION,
    "MI_dir_L3_mean" DOUBLE PRECISION,
    "MI_dir_L3_variance" DOUBLE PRECISION,
    "MI_dir_L1_weight" DOUBLE PRECISION,
    "MI_dir_L1_mean" DOUBLE PRECISION,
    "MI_dir_L1_variance" DOUBLE PRECISION,
    "MI_dir_L0.1_weight" DOUBLE PRECISION,
    "MI_dir_L0.1_mean" DOUBLE PRECISION,
    "MI_dir_L0.1_variance" DOUBLE PRECISION,
    "MI_dir_L0.01_weight" DOUBLE PRECISION,
    "MI_dir_L0.01_mean" DOUBLE PRECISION,
    "MI_dir_L0.01_variance" DOUBLE PRECISION,
    "MI_src_L5_weight" DOUBLE PRECISION,
    "MI_src_L5_mean" DOUBLE PRECISION,
    "MI_src_L5_variance" DOUBLE PRECISION,
    "MI_src_L3_weight" DOUBLE PRECISION,
    "MI_src_L3_mean" DOUBLE PRECISION,
    "MI_src_L3_variance" DOUBLE PRECISION,
    "MI_src_L1_weight" DOUBLE PRECISION,
    "MI_src_L1_mean" DOUBLE PRECISION,
    "MI_src_L1_variance" DOUBLE PRECISION,
    "MI_src_L0.1_weight" DOUBLE PRECISION,
    "MI_src_L0.1_mean" DOUBLE PRECISION,
    "MI_src_L0.1_variance" DOUBLE PRECISION,
    "MI_src_L0.01_weight" DOUBLE PRECISION,
    "MI_src_L0.01_mean" DOUBLE PRECISION,
    "MI_src_L0.01_variance" DOUBLE PRECISION,
    "MI_src_p_L5_weight" DOUBLE PRECISION,
    "MI_src_p_L5_mean" DOUBLE PRECISION,
    "MI_src_p_L5_variance" DOUBLE PRECISION,
    "MI_src_p_L3_weight" DOUBLE PRECISION,
    "MI_src_p_L3_mean" DOUBLE PRECISION,
    "MI_src_p_L3_variance" DOUBLE PRECISION,
    "MI_src_p_L1_weight" DOUBLE PRECISION,
    "MI_src_p_L1_mean" DOUBLE PRECISION,
    "MI_src_p_L1_variance" DOUBLE PRECISION,
    "MI_src_p_L0.1_weight" DOUBLE PRECISION,
    "MI_src_p_L0.1_mean" DOUBLE PRECISION,
    "MI_src_p_L0.1_variance" DOUBLE PRECISION,
    "MI_src_p_L0.01_weight" DOUBLE PRECISION,
    "MI_src_p_L0.01_mean" DOUBLE PRECISION,
    "MI_src_p_L0.01_variance" DOUBLE PRECISION,
    "HI_dir_L5_weight" DOUBLE PRECISION,
    "HI_dir_L5_mean" DOUBLE PRECISION,
    "HI_dir_L5_variance" DOUBLE PRECISION,
    "HI_dir_L3_weight" DOUBLE PRECISION,
    "HI_dir_L3_mean" DOUBLE PRECISION,
    "HI_dir_L3_variance" DOUBLE PRECISION,
    "HI_dir_L1_weight" DOUBLE PRECISION,
    "HI_dir_L1_mean" DOUBLE PRECISION,
    "HI_dir_L1_variance" DOUBLE PRECISION,
    "HI_dir_L0.1_weight" DOUBLE PRECISION,
    "HI_dir_L0.1_mean" DOUBLE PRECISION,
    "HI_dir_L0.1_variance" DOUBLE PRECISION,
    "HI_dir_L0.01_weight" DOUBLE PRECISION,
    "HI_dir_L0.01_mean" DOUBLE PRECISION,
    "HI_dir_L0.01_variance" DOUBLE PRECISION
);

COMMENT ON TABLE iot_raw_data IS 'Source table for IoT traffic data, monitored by Debezium for CDC.';