from datetime import timedelta
from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float64, String
from feast.data_format import ParquetFormat
from feast.value_type import ValueType
from feast.infra.offline_stores.contrib.spark_offline_store.spark_source import SparkSource

# Define an entity - the object these features are about.
# This assumes your source data has a 'device_name' column.
device_entity = Entity(name="device_name", description="An IoT device", value_type=ValueType.STRING)

# Point Feast to your preprocessed data (the output of ingest_raw_data.py).
# # This is your "Bronze" table where features have been calculated.
# bronze_table_source = FileSource(
#     name="nbiot_bronze_source",
#     path="s3a://processed/iot_traffic_bronze",
#     s3_endpoint_override="http://localhost:9000", 
#     timestamp_field="event_timestamp", 
#     created_timestamp_column="created",
#     file_format=ParquetFormat(),
# )

bronze_table_source = SparkSource(
    name="nbiot_bronze_source",
    # table="nbiot_bronze_delta_table",
    path="s3a://processed/iot_traffic_bronze/",
    # IMPORTANT: Your source data must have a timestamp column.
    # I've used 'event_timestamp'. You must add this in your Spark script.
    file_format="delta",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# Define a Feature View, which is a logical group of features.
nbiot_feature_view = FeatureView(
    name="nbiot_features",
    entities=[device_entity],
    ttl=timedelta(days=365),
    source=bronze_table_source,
    schema=[
        Field(name="MI_dir_L5_weight", dtype=Float64),
        Field(name="MI_dir_L5_mean", dtype=Float64),
        Field(name="MI_dir_L5_variance", dtype=Float64),
        Field(name="MI_dir_L3_weight", dtype=Float64),
        Field(name="MI_dir_L3_mean", dtype=Float64),
        Field(name="MI_dir_L3_variance", dtype=Float64),
        Field(name="MI_dir_L1_weight", dtype=Float64),
        Field(name="MI_dir_L1_mean", dtype=Float64),
        Field(name="MI_dir_L1_variance", dtype=Float64),
        Field(name="MI_dir_L0_1_weight", dtype=Float64),
        Field(name="MI_dir_L0_1_mean", dtype=Float64),
        Field(name="MI_dir_L0_1_variance", dtype=Float64),
        Field(name="MI_dir_L0_01_weight", dtype=Float64),
        Field(name="MI_dir_L0_01_mean", dtype=Float64),
        Field(name="MI_dir_L0_01_variance", dtype=Float64),
        Field(name="H_L5_weight", dtype=Float64),
        Field(name="H_L5_mean", dtype=Float64),
        Field(name="H_L5_variance", dtype=Float64),
        Field(name="H_L3_weight", dtype=Float64),
        Field(name="H_L3_mean", dtype=Float64),
        Field(name="H_L3_variance", dtype=Float64),
        Field(name="H_L1_weight", dtype=Float64),
        Field(name="H_L1_mean", dtype=Float64),
        Field(name="H_L1_variance", dtype=Float64),
        Field(name="H_L0_1_weight", dtype=Float64),
        Field(name="H_L0_1_mean", dtype=Float64),
        Field(name="H_L0_1_variance", dtype=Float64),
        Field(name="H_L0_01_weight", dtype=Float64),
        Field(name="H_L0_01_mean", dtype=Float64),
        Field(name="H_L0_01_variance", dtype=Float64),
        Field(name="HH_L5_weight", dtype=Float64),
        Field(name="HH_L5_mean", dtype=Float64),
        Field(name="HH_L5_std", dtype=Float64),
        Field(name="HH_L5_magnitude", dtype=Float64),
        Field(name="HH_L5_radius", dtype=Float64),
        Field(name="HH_L5_covariance", dtype=Float64),
        Field(name="HH_L5_pcc", dtype=Float64),
        Field(name="HH_L3_weight", dtype=Float64),
        Field(name="HH_L3_mean", dtype=Float64),
        Field(name="HH_L3_std", dtype=Float64),
        Field(name="HH_L3_magnitude", dtype=Float64),
        Field(name="HH_L3_radius", dtype=Float64),
        Field(name="HH_L3_covariance", dtype=Float64),
        Field(name="HH_L3_pcc", dtype=Float64),
        Field(name="HH_L1_weight", dtype=Float64),
        Field(name="HH_L1_mean", dtype=Float64),
        Field(name="HH_L1_std", dtype=Float64),
        Field(name="HH_L1_magnitude", dtype=Float64),
        Field(name="HH_L1_radius", dtype=Float64),
        Field(name="HH_L1_covariance", dtype=Float64),
        Field(name="HH_L1_pcc", dtype=Float64),
        Field(name="HH_L0_1_weight", dtype=Float64),
        Field(name="HH_L0_1_mean", dtype=Float64),
        Field(name="HH_L0_1_std", dtype=Float64),
        Field(name="HH_L0_1_magnitude", dtype=Float64),
        Field(name="HH_L0_1_radius", dtype=Float64),
        Field(name="HH_L0_1_covariance", dtype=Float64),
        Field(name="HH_L0_1_pcc", dtype=Float64),
        Field(name="HH_L0_01_weight", dtype=Float64),
        Field(name="HH_L0_01_mean", dtype=Float64),
        Field(name="HH_L0_01_std", dtype=Float64),
        Field(name="HH_L0_01_magnitude", dtype=Float64),
        Field(name="HH_L0_01_radius", dtype=Float64),
        Field(name="HH_L0_01_covariance", dtype=Float64),
        Field(name="HH_L0_01_pcc", dtype=Float64),
        Field(name="HH_jit_L5_weight", dtype=Float64),
        Field(name="HH_jit_L5_mean", dtype=Float64),
        Field(name="HH_jit_L5_variance", dtype=Float64),
        Field(name="HH_jit_L3_weight", dtype=Float64),
        Field(name="HH_jit_L3_mean", dtype=Float64),
        Field(name="HH_jit_L3_variance", dtype=Float64),
        Field(name="HH_jit_L1_weight", dtype=Float64),
        Field(name="HH_jit_L1_mean", dtype=Float64),
        Field(name="HH_jit_L1_variance", dtype=Float64),
        Field(name="HH_jit_L0_1_weight", dtype=Float64),
        Field(name="HH_jit_L0_1_mean", dtype=Float64),
        Field(name="HH_jit_L0_1_variance", dtype=Float64),
        Field(name="HH_jit_L0_01_weight", dtype=Float64),
        Field(name="HH_jit_L0_01_mean", dtype=Float64),
        Field(name="HH_jit_L0_01_variance", dtype=Float64),
        Field(name="HpHp_L5_weight", dtype=Float64),
        Field(name="HpHp_L5_mean", dtype=Float64),
        Field(name="HpHp_L5_std", dtype=Float64),
        Field(name="HpHp_L5_magnitude", dtype=Float64),
        Field(name="HpHp_L5_radius", dtype=Float64),
        Field(name="HpHp_L5_covariance", dtype=Float64),
        Field(name="HpHp_L5_pcc", dtype=Float64),
        Field(name="HpHp_L3_weight", dtype=Float64),
        Field(name="HpHp_L3_mean", dtype=Float64),
        Field(name="HpHp_L3_std", dtype=Float64),
        Field(name="HpHp_L3_magnitude", dtype=Float64),
        Field(name="HpHp_L3_radius", dtype=Float64),
        Field(name="HpHp_L3_covariance", dtype=Float64),
        Field(name="HpHp_L3_pcc", dtype=Float64),
        Field(name="HpHp_L1_weight", dtype=Float64),
        Field(name="HpHp_L1_mean", dtype=Float64),
        Field(name="HpHp_L1_std", dtype=Float64),
        Field(name="HpHp_L1_magnitude", dtype=Float64),
        Field(name="HpHp_L1_radius", dtype=Float64),
        Field(name="HpHp_L1_covariance", dtype=Float64),
        Field(name="HpHp_L1_pcc", dtype=Float64),
        Field(name="HpHp_L0_1_weight", dtype=Float64),
        Field(name="HpHp_L0_1_mean", dtype=Float64),
        Field(name="HpHp_L0_1_std", dtype=Float64),
        Field(name="HpHp_L0_1_magnitude", dtype=Float64),
        Field(name="HpHp_L0_1_radius", dtype=Float64),
        Field(name="HpHp_L0_1_covariance", dtype=Float64),
        Field(name="HpHp_L0_1_pcc", dtype=Float64),
        Field(name="HpHp_L0_01_weight", dtype=Float64),
        Field(name="HpHp_L0_01_mean", dtype=Float64),
        Field(name="HpHp_L0_01_std", dtype=Float64),
        Field(name="HpHp_L0_01_magnitude", dtype=Float64),
        Field(name="HpHp_L0_01_radius", dtype=Float64),
        Field(name="HpHp_L0_01_covariance", dtype=Float64),
        Field(name="HpHp_L0_01_pcc", dtype=Float64),
        Field(name="label", dtype=String) # Also including the label
    ]
)