from datetime import timedelta
from feast import Entity, FeatureView, FileSource, Feature
from feast.types import Float64, String

# Define an entity - the object these features are about.
# This assumes your source data has a 'device_name' column.
device_entity = Entity(name="device_name", description="An IoT device")

# Point Feast to your preprocessed data (the output of ingest_raw_data.py).
# This is your "Bronze" table where features have been calculated.
bronze_table_source = FileSource(
    name="nbiot_bronze_source",
    path="s3a://processed/temp_transform",
    # IMPORTANT: Your source data must have a timestamp column.
    # I've used 'event_timestamp'. You must add this in your Spark script.
    timestamp_field="event_timestamp", 
)

# Define a Feature View, which is a logical group of features.
nbiot_feature_view = FeatureView(
    name="nbiot_features",
    entities=[device_entity],
    ttl=timedelta(days=365),
    source=bronze_table_source,
    schema=[
        Feature(name="MI_dir_L5_weight", dtype=Float64),
        Feature(name="MI_dir_L5_mean", dtype=Float64),
        Feature(name="MI_dir_L5_variance", dtype=Float64),
        Feature(name="MI_dir_L3_weight", dtype=Float64),
        Feature(name="MI_dir_L3_mean", dtype=Float64),
        Feature(name="MI_dir_L3_variance", dtype=Float64),
        Feature(name="MI_dir_L1_weight", dtype=Float64),
        Feature(name="MI_dir_L1_mean", dtype=Float64),
        Feature(name="MI_dir_L1_variance", dtype=Float64),
        Feature(name="MI_dir_L0_1_weight", dtype=Float64),
        Feature(name="MI_dir_L0_1_mean", dtype=Float64),
        Feature(name="MI_dir_L0_1_variance", dtype=Float64),
        Feature(name="MI_dir_L0_01_weight", dtype=Float64),
        Feature(name="MI_dir_L0_01_mean", dtype=Float64),
        Feature(name="MI_dir_L0_01_variance", dtype=Float64),
        Feature(name="H_L5_weight", dtype=Float64),
        Feature(name="H_L5_mean", dtype=Float64),
        Feature(name="H_L5_variance", dtype=Float64),
        Feature(name="H_L3_weight", dtype=Float64),
        Feature(name="H_L3_mean", dtype=Float64),
        Feature(name="H_L3_variance", dtype=Float64),
        Feature(name="H_L1_weight", dtype=Float64),
        Feature(name="H_L1_mean", dtype=Float64),
        Feature(name="H_L1_variance", dtype=Float64),
        Feature(name="H_L0_1_weight", dtype=Float64),
        Feature(name="H_L0_1_mean", dtype=Float64),
        Feature(name="H_L0_1_variance", dtype=Float64),
        Feature(name="H_L0_01_weight", dtype=Float64),
        Feature(name="H_L0_01_mean", dtype=Float64),
        Feature(name="H_L0_01_variance", dtype=Float64),
        Feature(name="HH_L5_weight", dtype=Float64),
        Feature(name="HH_L5_mean", dtype=Float64),
        Feature(name="HH_L5_std", dtype=Float64),
        Feature(name="HH_L5_magnitude", dtype=Float64),
        Feature(name="HH_L5_radius", dtype=Float64),
        Feature(name="HH_L5_covariance", dtype=Float64),
        Feature(name="HH_L5_pcc", dtype=Float64),
        Feature(name="HH_L3_weight", dtype=Float64),
        Feature(name="HH_L3_mean", dtype=Float64),
        Feature(name="HH_L3_std", dtype=Float64),
        Feature(name="HH_L3_magnitude", dtype=Float64),
        Feature(name="HH_L3_radius", dtype=Float64),
        Feature(name="HH_L3_covariance", dtype=Float64),
        Feature(name="HH_L3_pcc", dtype=Float64),
        Feature(name="HH_L1_weight", dtype=Float64),
        Feature(name="HH_L1_mean", dtype=Float64),
        Feature(name="HH_L1_std", dtype=Float64),
        Feature(name="HH_L1_magnitude", dtype=Float64),
        Feature(name="HH_L1_radius", dtype=Float64),
        Feature(name="HH_L1_covariance", dtype=Float64),
        Feature(name="HH_L1_pcc", dtype=Float64),
        Feature(name="HH_L0_1_weight", dtype=Float64),
        Feature(name="HH_L0_1_mean", dtype=Float64),
        Feature(name="HH_L0_1_std", dtype=Float64),
        Feature(name="HH_L0_1_magnitude", dtype=Float64),
        Feature(name="HH_L0_1_radius", dtype=Float64),
        Feature(name="HH_L0_1_covariance", dtype=Float64),
        Feature(name="HH_L0_1_pcc", dtype=Float64),
        Feature(name="HH_L0_01_weight", dtype=Float64),
        Feature(name="HH_L0_01_mean", dtype=Float64),
        Feature(name="HH_L0_01_std", dtype=Float64),
        Feature(name="HH_L0_01_magnitude", dtype=Float64),
        Feature(name="HH_L0_01_radius", dtype=Float64),
        Feature(name="HH_L0_01_covariance", dtype=Float64),
        Feature(name="HH_L0_01_pcc", dtype=Float64),
        Feature(name="HH_jit_L5_weight", dtype=Float64),
        Feature(name="HH_jit_L5_mean", dtype=Float64),
        Feature(name="HH_jit_L5_variance", dtype=Float64),
        Feature(name="HH_jit_L3_weight", dtype=Float64),
        Feature(name="HH_jit_L3_mean", dtype=Float64),
        Feature(name="HH_jit_L3_variance", dtype=Float64),
        Feature(name="HH_jit_L1_weight", dtype=Float64),
        Feature(name="HH_jit_L1_mean", dtype=Float64),
        Feature(name="HH_jit_L1_variance", dtype=Float64),
        Feature(name="HH_jit_L0_1_weight", dtype=Float64),
        Feature(name="HH_jit_L0_1_mean", dtype=Float64),
        Feature(name="HH_jit_L0_1_variance", dtype=Float64),
        Feature(name="HH_jit_L0_01_weight", dtype=Float64),
        Feature(name="HH_jit_L0_01_mean", dtype=Float64),
        Feature(name="HH_jit_L0_01_variance", dtype=Float64),
        Feature(name="HpHp_L5_weight", dtype=Float64),
        Feature(name="HpHp_L5_mean", dtype=Float64),
        Feature(name="HpHp_L5_std", dtype=Float64),
        Feature(name="HpHp_L5_magnitude", dtype=Float64),
        Feature(name="HpHp_L5_radius", dtype=Float64),
        Feature(name="HpHp_L5_covariance", dtype=Float64),
        Feature(name="HpHp_L5_pcc", dtype=Float64),
        Feature(name="HpHp_L3_weight", dtype=Float64),
        Feature(name="HpHp_L3_mean", dtype=Float64),
        Feature(name="HpHp_L3_std", dtype=Float64),
        Feature(name="HpHp_L3_magnitude", dtype=Float64),
        Feature(name="HpHp_L3_radius", dtype=Float64),
        Feature(name="HpHp_L3_covariance", dtype=Float64),
        Feature(name="HpHp_L3_pcc", dtype=Float64),
        Feature(name="HpHp_L1_weight", dtype=Float64),
        Feature(name="HpHp_L1_mean", dtype=Float64),
        Feature(name="HpHp_L1_std", dtype=Float64),
        Feature(name="HpHp_L1_magnitude", dtype=Float64),
        Feature(name="HpHp_L1_radius", dtype=Float64),
        Feature(name="HpHp_L1_covariance", dtype=Float64),
        Feature(name="HpHp_L1_pcc", dtype=Float64),
        Feature(name="HpHp_L0_1_weight", dtype=Float64),
        Feature(name="HpHp_L0_1_mean", dtype=Float64),
        Feature(name="HpHp_L0_1_std", dtype=Float64),
        Feature(name="HpHp_L0_1_magnitude", dtype=Float64),
        Feature(name="HpHp_L0_1_radius", dtype=Float64),
        Feature(name="HpHp_L0_1_covariance", dtype=Float64),
        Feature(name="HpHp_L0_1_pcc", dtype=Float64),
        Feature(name="HpHp_L0_01_weight", dtype=Float64),
        Feature(name="HpHp_L0_01_mean", dtype=Float64),
        Feature(name="HpHp_L0_01_std", dtype=Float64),
        Feature(name="HpHp_L0_01_magnitude", dtype=Float64),
        Feature(name="HpHp_L0_01_radius", dtype=Float64),
        Feature(name="HpHp_L0_01_covariance", dtype=Float64),
        Feature(name="HpHp_L0_01_pcc", dtype=Float64),
        Feature(name="label", dtype=String) # Also including the label
    ]
)